import { define_chessboard, } from "./core.js";

export {
    ChessboardElement,
    configure_chessboard_assets,
    define_chessboard,
    PgnReplay,
    STANDARD_RULES_PROVIDER,
} from "./core.js";
export type {
    AccessibilityOptions,
    Annotation,
    AnnotationOptions,
    AnnotationsDetail,
    BoardLabels,
    BoardMark,
    BoardRenderers,
    BoardSound,
    BoardTheme,
    CapturedPieceDisplay,
    ChangeReason,
    ChangeSource,
    ChessboardAssets,
    ChessboardChangeDetail,
    ChessboardErrorDetail,
    ChessboardMoveDetail,
    ChessboardOptions,
    ChessboardPositionDetail,
    ChessboardStatus,
    Color,
    CustomizationOptions,
    HistoryState,
    InteractionOptions,
    KeyboardShortcuts,
    MarkColor,
    MaterialContext,
    Move,
    MoveInput,
    MoveRequest,
    MoveRequestEndDetail,
    Orientation,
    Piece,
    PieceKey,
    PieceOptions,
    PieceRenderer,
    PieceSymbol,
    PromotionOptions,
    PromotionRequest,
    QualityProfile,
    ResolvedChessboardOptions,
    ResolvedCustomization,
    RulesGame,
    RulesProvider,
    SoundOptions,
    Square,
    SquareContext,
} from "./core.js";

define_chessboard();
